### ISSUE TITLE
don't include characters which are only "-"

### ISSUE THREAD

**Issue by LinguList** [lexibank/tls#4] opened 2018-06-21 11:59 UTC
our current cldf does not check for "-", which seems to serve as a symbol for missing data.

**Comment by xrotwang** [comment] 2018-06-21 12:09
You could specify this in the JSON description using a [null property](https://www.w3.org/TR/tabular-metadata/#cell-null) on the column description.

**Comment by LinguList** [comment] 2018-06-21 12:12
Okay, so @tresoldi, please check which empty colummns are in the data (maybe it's more than just the dash), when preparing this dataset.

**Comment by xrotwang** [comment] 2018-06-21 12:15
@LinguList do you mean complete forms are just `-`? If so, I'd say these forms should not make it into the CLDF at all. This could be done with a custom `split_forms` method.

**Comment by LinguList** [comment] 2018-06-21 12:18
check second line (ID 2) for example:

```
2,,bondei1,kindofpoisonoussnake,-,-,,,,,
```
this is obviously a missing entry.

I can't re-create the cldf for some stupid reasons, and I can't even load tls, due to some error I can't trace:

```
Traceback (most recent call last):
  File "/home/jmlist/.pythonvenv/bin/lexibank", line 11, in <module>
    load_entry_point('pylexibank', 'console_scripts', 'lexibank')()
  File "/home/jmlist/data/datasets/lexibank-new/pylexibank/src/pylexibank/__main__.py", line 120, in main
    sys.exit(parser.main())
  File "/home/jmlist/.pythonvenv/lib/python3.5/site-packages/clldutils-2.1.0-py3.5.egg/clldutils/clilib.py", line 109, in main
    catch_all=catch_all, parsed_args=args)
  File "/home/jmlist/.pythonvenv/lib/python3.5/site-packages/clldutils-2.1.0-py3.5.egg/clldutils/clilib.py", line 81, in main
    self.commands[args.command](args)
  File "/home/jmlist/.pythonvenv/lib/python3.5/site-packages/clldutils-2.1.0-py3.5.egg/clldutils/clilib.py", line 34, in __call__
    return self.func(args)
  File "/home/jmlist/data/datasets/lexibank-new/pylexibank/src/pylexibank/commands/misc.py", line 71, in load
    with_dataset(args, _load)
  File "/home/jmlist/data/datasets/lexibank-new/pylexibank/src/pylexibank/commands/util.py", line 25, in with_dataset
    func(get_dataset(args, dataset.id), **vars(args))
  File "/home/jmlist/data/datasets/lexibank-new/pylexibank/src/pylexibank/commands/util.py", line 33, in _load
    db.load(ds)
  File "/home/jmlist/data/datasets/lexibank-new/pylexibank/src/pylexibank/db.py", line 399, in load
    insert(db, t.name, keys, *rows)
  File "/home/jmlist/data/datasets/lexibank-new/pylexibank/src/pylexibank/db.py", line 75, in insert
    rows)
sqlite3.IntegrityError: FOREIGN KEY constraint failed
```

Otherwise, I'd just adjust it myself.

**Comment by xrotwang** [comment] 2018-06-21 13:01
ok, will have a look.

**Comment by xrotwang** [comment] 2018-06-21 13:12
Hm. on my machine `makecldf tls` doesn't raise an error. This one only shows up on `dbload tls` - which doesn't really have anything to do with CLDF creation.

**Comment by xrotwang** [comment] 2018-06-21 13:14
But when running `makecldf` you should have seen quite a few lines like
```
WARNING cldf/forms.csv:159802 Key many not found in table parameters.csv
WARNING cldf/forms.csv:159803 Key small not found in table parameters.csv
```
so, obviously, the dataset isn't in good shape yet, not even passing `cldf validate`.

**Comment by LinguList** [comment] 2018-06-21 13:23
I suppose, I'll leave this for the time being, as @tresoldi is anyway working on this for the final release of clics.

**Comment by tresoldi** [comment] 2018-06-27 12:42
I've removed the empty entries, should have checked it. `makecldf` raises me no error, but I still get the `FOREIGN KEY` constrain error with `dbload`. Still not sure if the problem is in the CognateTable or FormTable contrain, I'm working on it.

**Comment by SimonGreenhill** [comment] 2019-04-08 20:04
is this fixed now?

**Comment by SimonGreenhill** [comment] 2019-04-08 20:05
Looks like it's caught [here](https://github.com/lexibank/tls/blob/master/lexibank_tls.py#L67)

**Closed as completed by SimonGreenhill** 2019-04-08 20:05 UTC
