### ISSUE TITLE
strange error when loading cldf data

### ISSUE THREAD

**Issue by LinguList** [lexibank/tls#5] opened 2018-06-21 12:30 UTC
I can't find the reason for this error, it must have to do with the CLDF created?

```
Traceback (most recent call last):
  File "/home/jmlist/.pythonvenv/bin/lexibank", line 11, in <module>
    load_entry_point('pylexibank', 'console_scripts', 'lexibank')()
  File "/home/jmlist/data/datasets/lexibank-new/pylexibank/src/pylexibank/__main__.py", line 120, in main
    sys.exit(parser.main())
  File "/home/jmlist/.pythonvenv/lib/python3.5/site-packages/clldutils-2.1.0-py3.5.egg/clldutils/clilib.py", line 109, in main
    catch_all=catch_all, parsed_args=args)
  File "/home/jmlist/.pythonvenv/lib/python3.5/site-packages/clldutils-2.1.0-py3.5.egg/clldutils/clilib.py", line 81, in main
    self.commands[args.command](args)
  File "/home/jmlist/.pythonvenv/lib/python3.5/site-packages/clldutils-2.1.0-py3.5.egg/clldutils/clilib.py", line 34, in __call__
    return self.func(args)
  File "/home/jmlist/data/datasets/lexibank-new/pylexibank/src/pylexibank/commands/misc.py", line 71, in load
    with_dataset(args, _load)
  File "/home/jmlist/data/datasets/lexibank-new/pylexibank/src/pylexibank/commands/util.py", line 25, in with_dataset
    func(get_dataset(args, dataset.id), **vars(args))
  File "/home/jmlist/data/datasets/lexibank-new/pylexibank/src/pylexibank/commands/util.py", line 33, in _load
    db.load(ds)
  File "/home/jmlist/data/datasets/lexibank-new/pylexibank/src/pylexibank/db.py", line 399, in load
    insert(db, t.name, keys, *rows)
  File "/home/jmlist/data/datasets/lexibank-new/pylexibank/src/pylexibank/db.py", line 75, in insert
    rows)
sqlite3.IntegrityError: FOREIGN KEY constraint failed
```

**Comment by xrotwang** [comment] 2018-06-21 13:00
That's typically caused by sources referenced, but no bibtex file being present.

**Comment by LinguList** [comment] 2018-06-25 12:57
This is still not solved with me here on my machine! Does anybody have a working version where

```
lexibank load tls
```
works properly?

**Comment by SimonGreenhill** [comment] 2018-06-25 13:11
yes, I get the same error.

**Comment by tresoldi** [comment] 2018-06-27 15:31
After doing some stupid errors, even pushing an unresolved merge (don't work on lexibank while watching a football match), it should be working now. Please check when you have time.

**Comment by SimonGreenhill** [comment] 2019-04-08 19:57
Closing, unable to replicate

**Closed as completed by SimonGreenhill** 2019-04-08 19:57 UTC
